sudo: true
branches:
  only:
  - master
language: python
notifications:
  email:
    on_success: change
    on_failure: always
  irc: chat.freenode.net#dedupe
services:
  - postgresql
matrix:
  include:
  - os: linux
    python: 3.4
  - os: osx
    language: generic
    before_install:
      - brew update
      - brew install python3
      - virtualenv env -p python3
      - source env/bin/activate
    services:
      - postgresql
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- createdb schools
script:
- make database
